# Computing Robinson-Foulds distance between two trees (Distances between trees)
install.packages("ape")
install.packages("phangorn")
library(ape)
library(phangorn)
tree1 <- read.tree("/home/usuario/Documents/Phylogeny_RSV_RV/RV/Analysis_1/5_ML Phylogeny/2/2.1/alignment2.2 (copy).fasta.treefile")
tree2 <- read.tree("/home/usuario/Documents/Phylogeny_RSV_RV/RV/Analysis_1/5_ML Phylogeny/2/2.1/alignment2.2.fasta.treefile")
treedist(tree1,tree2)
RF_distance <- RF.dist(tree1, tree2)
print(RF_distance)
